#!/usr/bin/env python3
"""
Build an appendix-style LaTeX table for the SIC fallback used in the strict semiconductor seed.

This mirrors the SIC fallback described in Chapter 3 (§3.6): SIC 3674 is used as a strict
fallback when RBICS business-segment reporting is unavailable.

Counts are computed at the *firm level* (unique FactSet entity IDs) to avoid double-counting
when the same organization appears under multiple node representations in the multiplex
(e.g., SCR node and prime vendor identity node).

Output (default):
  - tables/chapter3/tab_app_sic_semiconductor_fallback.tex
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
import yaml


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Build appendix table: SIC fallback (strict semiconductors) with coverage count"
    )
    p.add_argument("--config", default="src/ch3/config/semiconductor_codes.yml")
    p.add_argument(
        "--nodes",
        default="artifacts/ch3/network_upstream/dod_semiconductor_nodes_top5_d99_shipping_strict.parquet",
        help="Locked strict DoD semiconductor network nodes parquet",
    )
    p.add_argument(
        "--semis-flags",
        default="artifacts/ch3/reference/semis_flags_strict.parquet",
        help="Node-level strict semis flags (built on the canonical multiplex nodes)",
    )
    p.add_argument(
        "--out",
        default="tables/chapter3/tab_app_sic_semiconductor_fallback.tex",
        help="Output .tex file (tabular-only)",
    )
    return p.parse_args()


def _load_sic_fallback_codes(cfg_path: Path) -> list[str]:
    cfg = yaml.safe_load(cfg_path.read_text())
    codes = [str(x) for x in cfg.get("sic_core", [])]
    # Strict build uses SIC 3674 only (see src/ch3/prediction/build_semis_catalog_strict.py)
    return [c for c in codes if c == "3674"] or ["3674"]


def _example_firms(nodes: pd.DataFrame, n: int = 3) -> str:
    df = nodes[nodes["is_semi_sic3674"].astype(bool) & nodes["name"].notna()].copy()
    if df.empty:
        return "---"
    if "pagerank" in df.columns:
        df = df.sort_values(["pagerank", "name"], ascending=[False, True])
    else:
        df = df.sort_values(["name"], ascending=[True])
    examples: list[str] = []
    for name in df["name"].astype(str):
        if name not in examples:
            examples.append(name)
        if len(examples) >= n:
            break
    return "; ".join(examples) if examples else "---"


def main() -> None:
    args = parse_args()
    cfg_path = Path(args.config)
    nodes_path = Path(args.nodes)
    semis_flags_path = Path(args.semis_flags)
    out_path = Path(args.out)

    for p in (cfg_path, nodes_path, semis_flags_path):
        if not p.exists():
            raise FileNotFoundError(p)

    sic_codes = _load_sic_fallback_codes(cfg_path)
    if "3674" not in sic_codes:
        raise ValueError(f"Expected SIC 3674 in sic_core; got {sic_codes}")

    # Node-level summary (for comments / sanity checks).
    nodes = pd.read_parquet(
        nodes_path, columns=["node_uid", "name", "pagerank", "is_semi_sic3674", "is_semi_rbics_l4"]
    )
    node_uids = set(nodes["node_uid"].astype(str))
    nodes_sic = int(nodes["is_semi_sic3674"].sum())
    nodes_sic_only = int((nodes["is_semi_sic3674"] & ~nodes["is_semi_rbics_l4"]).sum())

    # Firm-level counts (unique FactSet entity IDs) restricted to the locked strict network nodes.
    flags = pd.read_parquet(
        semis_flags_path,
        columns=["node_uid", "factset_entity_id", "is_semi_sic3674", "is_semi_rbics_l4"],
    )
    flags = flags[flags["node_uid"].astype(str).isin(node_uids)].copy()
    flags["factset_entity_id"] = flags["factset_entity_id"].astype(str)

    firm_sic = flags[flags["is_semi_sic3674"]]["factset_entity_id"].nunique()
    firm_sic_only = flags[(flags["is_semi_sic3674"]) & (~flags["is_semi_rbics_l4"])][
        "factset_entity_id"
    ].nunique()

    out_path.parent.mkdir(parents=True, exist_ok=True)

    # This table is intentionally minimal; interpretive notes belong in the dissertation text.
    examples = _example_firms(nodes, n=3)
    lines = [
        "% Auto-generated by src/ch3/analysis/build_semiconductor_codes_sic_fallback_table.py",
        f"% Locked strict network SIC counts: nodes_sic3674={nodes_sic}, nodes_sic_only={nodes_sic_only}, firms_sic3674={firm_sic}, firms_sic_only={firm_sic_only}",
        r"\begin{tabular}{@{}l l S[table-format=4.0, table-number-alignment=center] p{7.4cm}@{}}",
        r"\toprule",
        r"\multicolumn{1}{c}{SIC code} & \multicolumn{1}{c}{Industry} & \multicolumn{1}{c}{Firms} & \multicolumn{1}{c}{Example firms in DoD semiconductor network} \\",
        r"\midrule",
        f"3674 & Semiconductors and Related Devices & {firm_sic} & {examples} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ]
    out_path.write_text("\n".join(lines))
    print(f"[done] wrote {out_path}")


if __name__ == "__main__":
    main()
